import ForterABI from '../abis/Forter.json';
import ReputationNFTABI from '../abis/ReputationNFT.json';
import StakingPoolABI from '../abis/StakingPool.json';
import ForterGovernanceABI from '../abis/ForterGovernance.json';
import MockTokenABI from '../abis/MockToken.json';

/**
 * Contract addresses deployed on Base Sepolia
 * Auto-generated by scripts/update-frontend.sh
 */
export const contractAddresses = {
  forter: '0xaf1c459cb7fc9fd6e7e6f39f34b79412a1c6e859' as const,
  reputationNFT: '0x4ad56dfd89125a0f5ae28677f10d0f4ffc62cbde' as const,
  stakingPool: '' as const,
  governance: '0xfebf0b00a87f253709b9ddda6a8c8dd1b28eee20' as const,
  token: '0x6daab123d209cb36673fc50ce54c959ed5567f6d' as const,
} as const;

/**
 * Contract configurations with addresses and ABIs
 * Ready to use with wagmi/viem
 */
export const contracts = {
  forter: {
    address: contractAddresses.forter,
    abi: ForterABI,
  },
  reputationNFT: {
    address: contractAddresses.reputationNFT,
    abi: ReputationNFTABI,
  },
  stakingPool: {
    address: contractAddresses.stakingPool,
    abi: StakingPoolABI,
  },
  governance: {
    address: contractAddresses.governance,
    abi: ForterGovernanceABI,
  },
  token: {
    address: contractAddresses.token,
    abi: MockTokenABI,
  },
} as const;

// Re-export ABIs for direct access
export { ForterABI, ReputationNFTABI, StakingPoolABI, ForterGovernanceABI, MockTokenABI };
